api_reliable_start_date: '2007-01-01'
api_reliable_start_sequential_id: 4356
historical_era_draws_count: 4355
historical_era_end_date: '2006-12-31'
last_verified_date: '2026-02-01T20:34:57.598566'
lottery_start_date: '1957-01-27'
lottery_start_sequential_id: 1
total_draws_count: 7308
version: '1.0'
