api_reliable_start_date: '2007-01-01'
api_reliable_start_sequential_id: 4356
historical_era_draws_count: 4355
historical_era_end_date: '2006-12-31'
last_verified_date: '2026-01-13T20:27:24.613912'
lottery_start_date: '1957-01-27'
lottery_start_sequential_id: 1
total_draws_count: 7299
version: '1.0'
